version: "3"
services:
web:
  #Added Container Name
  container_name: web
  build: .
  #Added restart always
  restart: always
  ports:
    - 8888:80
  #Added the real direction of env file
  env_file:
    #- .env
    - ./example.env
  volumes:
    - .:/myportfolio
  depends_on:
    - db

db:
  #Added container_name
  container_name: db
  #Erased tag not found
  image: postgres
  restart: always
  env_file:
    - ./example.env
  volumes:
    - mydatabase:/var/lib/postgresql/data

volumes:
  mydatabase:
